### ISSUE TITLE
Mechanic Job

### ISSUE THREAD

**Issue by Austin-R418** [Austin-R418/TARP-Development-Tracker#62]
Ranks-
1Owner
2Manager
3Supervisor
4Driver
5Mechanic

Society Fund
Store at Bennys in LS and Flywheels in Sandy
FlyWheels interior
Working Lifts
Advanced car repair and upgrade
Possibly change sign at Bennys in LS to say bennys
Only mechanics can access the upgrade menu for civilian

**Comment by Austin-R418** [comment]
Get Volt the templates for the vehicles.

**Comment by Fitzie1414** [comment]
Confirmed Volt has vehicle templates

Changed location from Benny's to chop shop @ 229
Stated he does not want uniforms

Created separate script: esx_mechanicjob_jefe
Added FlyWheels interior - CAN HE HAVE MORE THAN ONE LOCATION??? NEED A DECISION ON THIS ONE

He requested separating the boss actions menu from the mechanic actions menu, I can attempt this but will guarantee nothing.

**Comment by Fitzie1414** [comment]
Changed location back to Benny's - Chop shop interior did not allow the markers to display

**Comment by theblitz1738** [comment]
Completed:
Per Volt - Picked Benny's (city) over FlyWheels (Sandy). Interior of chop shop at 229 did not work due to MLO file type. 

WIP:
Extract boss from main menu and create own menu and circle
Place Customs Shop inside Benny's
Make tow trucks purchasable by players - similar to how police buy vehicles from police garage
Sign Board Truck?
Crafting location and options?
