### ISSUE TITLE
New Heists

### ISSUE THREAD

**Issue by Fitzie1414** [Austin-R418/TARP-Development-Tracker#77]
Added to dev server for testing & prep:

esx_robatm
- Adds 6 ATM robberies around the map yielding 2,000-8,000 in dirty money.
- No police required to be on (can be changed in config)
- Current issues: Robbery marker & ATM access area overlap

esx_holdupbank
- Adds 8 bank robberies around the map yielding 75,000-200,000 in dirty money for most banks (4 cops required)
- Yield is 2,000,000-5,000,000 for the Pacific Standard Bank (6 cops required)
- Player needs to have a drill in order to access the bank (may change to a keycard they need to dumpster dive for)
- Current issues: Robberies won't start & notifications don't display

esx_holduppolice
- Adds possible heists at Mission Row PD, Sandy Sheriff's Office, and Paleto PD
- Yields drugs and/or dirty money
- Not tested yet

esx_vangelico_robbery
- Adds robbery at Vangelico's Jewlery Store
- 6 Cops required to rob & 6 cops required to sell the jewels
- Rewards between 800,000 and 2,550,000 depending on number of jewels processed and sold
- Not tested yet

**Comment by ItsTheSneakyTurtle** [comment]
for the police hold up they could yield some weaponry and ammunition too? I think Paleto PD would be the best location to do it too because, in terms of realism and realistic roleplay we strive for, in reality, MRPD would be bustling with cops, but Paleto, on the other hand, would be pretty dormant.
